/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "FCD-PDU-Descriptions"
 * 	found in "its_facilities_pdu_all.asn"
 * 	`asn1c -fnative-types -gen-PER`
 */

#ifndef	_Lat_H_
#define	_Lat_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Lat {
	Lat_oneMicrodegreeNorth	= 10,
	Lat_oneMicrodegreeSouth	= -10,
	Lat_unavailable	= 900000001
} e_Lat;

/* Lat */
typedef long	 Lat_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Lat;
asn_struct_free_f Lat_free;
asn_struct_print_f Lat_print;
asn_constr_check_f Lat_constraint;
ber_type_decoder_f Lat_decode_ber;
der_type_encoder_f Lat_encode_der;
xer_type_decoder_f Lat_decode_xer;
xer_type_encoder_f Lat_encode_xer;
per_type_decoder_f Lat_decode_uper;
per_type_encoder_f Lat_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Lat_H_ */
#include <asn_internal.h>
