/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "FCD-PDU-Descriptions"
 * 	found in "its_facilities_pdu_all.asn"
 * 	`asn1c -fnative-types -gen-PER`
 */

#ifndef	_Long_H_
#define	_Long_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Long {
	Long_oneMicrodegreeEast	= 10,
	Long_oneMicrodegreeWest	= -10,
	Long_unavailable	= 1800000001
} e_Long;

/* Long */
typedef long	 Long_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Long;
asn_struct_free_f Long_free;
asn_struct_print_f Long_print;
asn_constr_check_f Long_constraint;
ber_type_decoder_f Long_decode_ber;
der_type_encoder_f Long_encode_der;
xer_type_decoder_f Long_decode_xer;
xer_type_encoder_f Long_encode_xer;
per_type_decoder_f Long_decode_uper;
per_type_encoder_f Long_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Long_H_ */
#include <asn_internal.h>
