/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "FCD-PDU-Descriptions"
 * 	found in "its_facilities_pdu_all.asn"
 * 	`asn1c -fnative-types -gen-PER`
 */

#ifndef	_SourceID_H_
#define	_SourceID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SourceID */
typedef unsigned long	 SourceID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SourceID;
asn_struct_free_f SourceID_free;
asn_struct_print_f SourceID_print;
asn_constr_check_f SourceID_constraint;
ber_type_decoder_f SourceID_decode_ber;
der_type_encoder_f SourceID_encode_der;
xer_type_decoder_f SourceID_decode_xer;
xer_type_encoder_f SourceID_encode_xer;
per_type_decoder_f SourceID_decode_uper;
per_type_encoder_f SourceID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SourceID_H_ */
#include <asn_internal.h>
